import { FunctionComponent } from "react";
import styles from "./FrameComponent4.module.css";

export type FrameComponent4Type = {
  className?: string;
};

const FrameComponent4: FunctionComponent<FrameComponent4Type> = ({
  className = "",
}) => {
  return (
    <section className={[styles.homePageInner, className].join(" ")}>
      <div className={styles.frameParent}>
        <div className={styles.frameWrapper}>
          <div className={styles.todaysCryptocurrencyPricesParent}>
            <h1 className={styles.todaysCryptocurrencyPrices}>
              Today's Cryptocurrency Prices
            </h1>
            <div className={styles.designerWrapper}>
              <b className={styles.designer}> generated by SmallCapToken</b>
            </div>
          </div>
        </div>
        <div className={styles.frameGroup}>
          <div className={styles.frameContainer}>
            <div className={styles.overviewParent}>
              <div className={styles.overview}>Overview</div>
              <h2 className={styles.globalCryptoMarketContainer}>
                <p className={styles.globalCrypto}>Global crypto</p>
                <p className={styles.marketCap}>market cap</p>
              </h2>
            </div>
            <div className={styles.capitalizationParent}>
              <div className={styles.capitalization}>Capitalization</div>
              <div className={styles.tWrapper}>
                <div className={styles.t}>
                  <span>{`$ `}</span>
                  <span className={styles.t1}>2.44T</span>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.searchBackgroundParent}>
            <div className={styles.searchBackground} />
            <div className={styles.searchInputContainerWrapper}>
              <div className={styles.searchInputContainer}>
                <img
                  className={styles.background62Icon}
                  alt=""
                  src="/background6-2@2x.png"
                />
                <a
                  className={styles.searchCryptoCurrencies}
                >{`Search Crypto Currencies `}</a>
              </div>
            </div>
            <div className={styles.wrapperSearchNormal}>
              <img
                className={styles.searchNormalIcon}
                loading="lazy"
                alt=""
                src="/searchnormal.svg"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FrameComponent4;
